### PR TITLE
Add herm Option in CG and fix Bug in Test

### PR DESCRIPTION
**Pull request by SebastianSemper**
1. The CG Algorithm gets a herm option which yields a
speedup by factor of two.

2. Fix Bug in Testgeneration, which has set wrong sizes,
which lead to test crashes

### CODE REVIEW

**Comment by SebastianSemper** [comment]
The issues raised above together with some additional parameter renaming spitting down the same whole were added.

**Comment by SebastianSemper** [comment]
Using the following code
``
import fastmat; import numpy
x = numpy.random.randn(3)
A = fastmat.Eye(3)
fastmat.algs.CG(A,x)
``
results in `x` being a vector containing only zeros.

**Comment by ChristophWWagner** [comment]
could you please try this again with the current HEAD of cython-branch? I think of a bug that could cause this behaviour, which is fixed there.

**Comment by ChristophWWagner** [comment]
Problem detected.

**Comment by ChristophWWagner** [comment]
Fixed in eee59939fe1e0f92c5686e8626e3739472952758.
An explicit note was added to the documentation of the Eye and Matrix class about the return object of any transform potentially being a view into or the input array itself.

**Pull request merged**
