### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by ChristophWWagner**
Some bug fixes and extensions. Resolves issues #37, #39, #40, #41, #42, #44

Previous pull request was withdrawn.

### CODE REVIEW

**Comment by SebastianSemper** [comment]
So commit 124cf96 "cleans up code clarity"? Does this introduce some much needed chaos? :3

**Comment by ChristophWWagner** [comment]
Yeah. It's true. Totally clear to me. So sad.

**Comment by SebastianSemper** [comment]
Since we now have all these beautiful options, we should first document them all in the initialization of the base class.

**Comment by ChristophWWagner** [comment]
I shouldn't have cherry-picked the docu stuff from the int16 branch where it was pushed accidentially. Could have been easier just to accept it there, when this branch was still working ¯\_(ツ)_/¯

**Comment by SebastianSemper** [comment]
Well now that shit has hit the fan, how do we proceed? :3

**Comment by ChristophWWagner** [comment]
I do what I should hae done directly. Merge in int16 and do both pull requests at one. Currently having IT problems. Hopefully the VM starts after lunch or there is some shit that will hit the fan at hp support ;)

**Comment by SebastianSemper** [comment]
Alright. Let's see how this plays out. :) Good luck with the HP!

**Comment by ChristophWWagner** [comment]
Thanks, should be fine now. Happy approving! :)

**Pull request merged**
